profile::kubernetes::deployment_server::helm_user_group: deployment
profile::kubernetes::deployment_server::user_defaults:
  owner: mwdeploy
  group: deployment
  mode: "0640"

profile::kubernetes::deployment_server::services:
  main:
    mathoid:
      usernames:
        - name: mathoid
        - name: mathoid-deploy
    zotero:
      usernames:
        - name: zotero
        - name: zotero-deploy
    blubberoid:
      usernames:
        - name: blubberoid
        - name: blubberoid-deploy
    eventgate-analytics:
      usernames:
        - name: eventgate-analytics
        - name: eventgate-analytics-deploy
    eventgate-main:
      usernames:
        - name: eventgate-main
        - name: eventgate-main-deploy
    citoid:
      usernames:
        - name: citoid
        - name: citoid-deploy
    cxserver:
      usernames:
        - name: cxserver
        - name: cxserver-deploy
    sessionstore:
      usernames:
        - name: sessionstore
        - name: sessionstore-deploy
    termbox:
      usernames:
        - name: termbox
        - name: termbox-deploy
    wikifeeds:
      usernames:
        - name: wikifeeds
        - name: wikifeeds-deploy
    echostore:
      usernames:
        - name: echostore
        - name: echostore-deploy
    eventgate-logging-external:
      usernames:
        - name: eventgate-logging-external
        - name: eventgate-logging-external-deploy
    eventstreams:
      usernames:
        - name: eventstreams
        - name: eventstreams-deploy
    eventstreams-internal:
      usernames:
        - name: eventstreams-internal
        - name: eventstreams-internal-deploy
    eventgate-analytics-external:
      usernames:
        - name: eventgate-analytics-external
        - name: eventgate-analytics-external-deploy
    changeprop:
      usernames:
        - name: changeprop
        - name: changeprop-deploy
    changeprop-jobqueue:
      usernames:
        - name: changeprop-jobqueue
        - name: changeprop-jobqueue-deploy
    benthos-cache-invalidator:
      usernames:
        - name: benthos-cache-invalidator
        - name: benthos-cache-invalidator-deploy
    proton:
      usernames:
        - name: proton
        - name: proton-deploy
    mobileapps:
      usernames:
        - name: mobileapps
        - name: mobileapps-deploy
    recommendation-api:
      usernames:
        - name: recommendation-api
        - name: recommendation-api-deploy
    push-notifications:
      usernames:
        - name: push-notifications
        - name: push-notifications-deploy
    api-gateway:
      usernames:
        - name: api-gateway
        - name: api-gateway-deploy
    apertium:
      usernames:
        - name: apertium
        - name: apertium-deploy
    linkrecommendation:
      usernames:
        - name: linkrecommendation
        - name: linkrecommendation-deploy
    similar-users:
      usernames:
        - name: similar-users
        - name: similar-users-deploy
    shellbox:
      usernames:
        - name: shellbox
        - name: shellbox-deploy
    shellbox-constraints:
      usernames:
        - name: shellbox-constraints
        - name: shellbox-constraints-deploy
    shellbox-media:
      usernames:
        - name: shellbox-media
        - name: shellbox-media-deploy
    shellbox-syntaxhighlight:
      usernames:
        - name: shellbox-syntaxhighlight
        - name: shellbox-syntaxhighlight-deploy
    shellbox-timeline:
      usernames:
        - name: shellbox-timeline
        - name: shellbox-timeline-deploy
    machinetranslation:
      usernames:
        - name: machinetranslation
        - name: machinetranslation-deploy
    miscweb:
      usernames:
        - name: miscweb
        - name: miscweb-deploy
    mw-debug:
      usernames:
        - name: mw-debug
        - name: mw-debug-deploy
    mw-api-int:
      usernames:
        - name: mw-api-int
        - name: mw-api-int-deploy
    mw-api-ext:
      usernames:
        - name: mw-api-ext
        - name: mw-api-ext-deploy
    mw-jobrunner:
      usernames:
        - name: mw-jobrunner
        - name: mw-jobrunner-deploy
    mw-parsoid:
      usernames:
        - name: mw-parsoid
        - name: mw-parsoid-deploy
    mw-page-content-change-enrich:
      usernames:
        - name: mw-page-content-change-enrich
        - name: mw-page-content-change-enrich-deploy
    mw-web:
      usernames:
        - name: mw-web
        - name: mw-web-deploy
    mw-misc:
      usernames:
        - name: mw-misc
        - name: mw-misc-deploy
    mw-script:
      usernames:
        - name: mw-script
        - name: mw-script-deploy
    mw-videoscaler:
      usernames:
        - name: mw-videoscaler
        - name: mw-videoscaler-deploy
    mw-wikifunctions:
      usernames:
        - name: mw-wikifunctions
        - name: mw-wikifunctions-deploy
    tegola-vector-tiles:
      usernames:
        - name: tegola-vector-tiles
        - name: tegola-vector-tiles-deploy
    rdf-streaming-updater:
      usernames:
        - name: rdf-streaming-updater
        - name: rdf-streaming-updater-deploy
    toolhub:
      usernames:
        - name: toolhub
        - name: toolhub-deploy
    datahub:
      usernames:
        - name: datahub
        - name: datahub-deploy
    developer-portal:
      usernames:
        - name: developer-portal
        - name: developer-portal-deploy
    image-suggestion:
      usernames:
        - name: image-suggestion
        - name: image-suggestion-deploy
    thumbor:
      usernames:
        - name: thumbor
        - name: thumbor-deploy
    device-analytics:
      usernames:
        - name: device-analytics
        - name: device-analytics-deploy
    rest-gateway:
      usernames:
        - name: rest-gateway
        - name: rest-gateway-deploy
    ipoid:
      usernames:
        - name: ipoid
        - name: ipoid-deploy
    opentelemetry-collector:
      usernames:
        - name: opentelemetry-collector
        - name: opentelemetry-collector-deploy
    wikifunctions:
      usernames:
        - name: wikifunctions
        - name: wikifunctions-deploy
    geo-analytics:
      usernames:
        - name: geo-analytics
        - name: geo-analytics-deploy
    media-analytics:
      usernames:
        - name: media-analytics
        - name: media-analytics-deploy
    edit-analytics:
      usernames:
        - name: edit-analytics
        - name: edit-analytics-deploy
    editor-analytics:
      usernames:
        - name: editor-analytics
        - name: editor-analytics-deploy
    page-analytics:
      usernames:
        - name: page-analytics
        - name: page-analytics-deploy
    cirrus-streaming-updater:
      usernames:
        - name: cirrus-streaming-updater
        - name: cirrus-streaming-updater-deploy
  ml-serve:
    revscoring-editquality-goodfaith:
      usernames:
        - name: revscoring-editquality-goodfaith
          owner: root
          group: deploy-ml-service
        - name: revscoring-editquality-goodfaith-deploy
          owner: root
          group: deploy-ml-service
    revscoring-editquality-damaging:
      usernames:
        - name: revscoring-editquality-damaging
          owner: root
          group: deploy-ml-service
        - name: revscoring-editquality-damaging-deploy
          owner: root
          group: deploy-ml-service
    revscoring-editquality-reverted:
      usernames:
        - name: revscoring-editquality-reverted
          owner: root
          group: deploy-ml-service
        - name: revscoring-editquality-reverted-deploy
          owner: root
          group: deploy-ml-service
    revscoring-draftquality:
      usernames:
        - name: revscoring-draftquality
          owner: root
          group: deploy-ml-service
        - name: revscoring-draftquality-deploy
          owner: root
          group: deploy-ml-service
    revscoring-articlequality:
      usernames:
        - name: revscoring-articlequality
          owner: root
          group: deploy-ml-service
        - name: revscoring-articlequality-deploy
          owner: root
          group: deploy-ml-service
    revscoring-articletopic:
      usernames:
        - name: revscoring-articletopic
          owner: root
          group: deploy-ml-service
        - name: revscoring-articletopic-deploy
          owner: root
          group: deploy-ml-service
    revscoring-drafttopic:
      usernames:
        - name: revscoring-drafttopic
          owner: root
          group: deploy-ml-service
        - name: revscoring-drafttopic-deploy
          owner: root
          group: deploy-ml-service
    articletopic-outlink:
      usernames:
        - name: articletopic-outlink
          owner: root
          group: deploy-ml-service
        - name: articletopic-outlink-deploy
          owner: root
          group: deploy-ml-service
    revertrisk:
      usernames:
        - name: revertrisk
          owner: root
          group: deploy-ml-service
        - name: revertrisk-deploy
          owner: root
          group: deploy-ml-service
    readability:
      usernames:
        - name: readability
          owner: root
          group: deploy-ml-service
        - name: readability-deploy
          owner: root
          group: deploy-ml-service
    article-descriptions:
      usernames:
        - name: article-descriptions
          owner: root
          group: deploy-ml-service
        - name: article-descriptions-deploy
          owner: root
          group: deploy-ml-service
    ores-legacy:
      usernames:
        - name: ores-legacy
          owner: root
          group: deploy-ml-service
        - name: ores-legacy-deploy
          owner: root
          group: deploy-ml-service
    recommendation-api-ng:
      usernames:
        - name: recommendation-api-ng
          owner: root
          group: deploy-ml-service
        - name: recommendation-api-ng-deploy
          owner: root
          group: deploy-ml-service
    llm:
      usernames:
        - name: llm
          owner: root
          group: deploy-ml-service
        - name: llm-deploy
          owner: root
          group: deploy-ml-service
    experimental:
      usernames:
        - name: experimental
          owner: root
          group: deploy-ml-service
        - name: experimental-deploy
          owner: root
          group: deploy-ml-service
        - name: experimental-debug
          owner: root
          group: deploy-ml-service
  dse-k8s:
    rdf-streaming-updater:
      usernames:
        - name: rdf-streaming-updater
        - name: rdf-streaming-updater-deploy
    spark:
      usernames:
        - name: spark
        - name: spark-deploy
    spark-history-test:
      usernames:
        - name: spark-history-test
          owner: root
          group: analytics-deployers
        - name: spark-history-test-deploy
          owner: root
          group: analytics-deployers
    spark-history:
      usernames:
        - name: spark-history
          owner: root
          group: analytics-deployers
        - name: spark-history-deploy
          owner: root
          group: analytics-deployers
    stream-enrichment-poc:
      usernames:
        - name: stream-enrichment-poc
        - name: stream-enrichment-poc-deploy
    superset:
      usernames:
        - name: superset
          owner: root
          group: analytics-deployers
        - name: superset-deploy
          owner: root
          group: analytics-deployers
    superset-next:
      usernames:
        - name: superset-next
          owner: root
          group: analytics-deployers
        - name: superset-next-deploy
          owner: root
          group: analytics-deployers
    echoserver:
      usernames:
        - name: echoserver
        - name: echoserver-deploy
  aux-k8s:
    jaeger:
      usernames:
        - name: jaeger
        - name: jaeger-deploy
