profile::alertmanager::api::vhost_alias: 'alertmanager-*.%{facts.domain}'
profile::alertmanager::api::ro: []
profile::alertmanager::api::rw:
  - 'grafana1002.eqiad.wmnet'
  - 'grafana2001.codfw.wmnet'
  - 'netmon1003.wikimedia.org'
  - 'netmon2002.wikimedia.org'
  - 'cumin1002.eqiad.wmnet'
  - 'cumin2002.codfw.wmnet'
  - 'cuminunpriv1001.eqiad.wmnet'
  - 'cloudcumin1001.eqiad.wmnet'
  - 'cloudcumin2001.codfw.wmnet'
