cluster: wmcs
profile::prometheus::memcached_exporter::arguments: '--memcached.address=localhost:11000'
contactgroups: wmcs-team
mgmt_contactgroups: wmcs-team-email
# See T224828
raid::md::cron_ensure: absent
