- name: default
  also_notifies: []
  attributes: {}
  description: Pool for eqiad1/cloudservices1003
  id: 794ccc2c-d751-44fe-b57f-8894c9f5c842
  nameservers:
  - host: 208.80.155.117
    port: 53
  - host: 208.80.154.12
    port: 53
  - host: 208.80.154.135
    port: 53
  - host: 208.80.154.11
    port: 53
  ns_records:
  - hostname: labs-ns0.wikimedia.org.
    priority: 10
  - hostname: labs-ns1.wikimedia.org.
    priority: 11
  - hostname: labs-ns2.wikimedia.org.
    priority: 12
  - hostname: labs-ns3.wikimedia.org.
    priority: 13
  targets:
  - masters:
    - host: 208.80.155.117
      port: 5354
    - host: 208.80.154.135
      port: 5354
    options:
      connection: mysql://pdns:<password>@208.80.155.117/pdns
      host: 208.80.155.117
      port: '53'
    type: powerdns
  - masters:
    - host: 208.80.155.117
      port: 5354
    - host: 208.80.154.135
      port: 5354
    options:
      connection: mysql://pdns:<password>@208.80.154.12/pdns
      host: 208.80.154.12
      port: '53'
    type: powerdns
  - masters:
    - host: 208.80.155.117
      port: 5354
    - host: 208.80.154.135
      port: 5354
    options:
      connection: mysql://pdns:<password>@208.80.154.135/pdns
      host: 208.80.154.135
      port: '53'
    type: powerdns
  - masters:
    - host: 208.80.155.117
      port: 5354
    - host: 208.80.154.135
      port: 5354
    options:
      connection: mysql://pdns:<password>@208.80.154.11/pdns
      host: 208.80.154.11
      port: '53'
    type: powerdns
