groups:
- name: alerts_beta.conf
  rules:
  - alert: InstanceDiskFullCrit
    expr: (node_filesystem_avail{fstype!~"(rpc_pipefs|rootfs)"} / node_filesystem_size)
      * 100 < 5
    for: 15m
    labels:
      severity: crit
    annotations:
      SUMMARY: '{{$labels.instance}} FS {{$labels.mountpoint}} at {{ printf "%3.2f"
        $value }}% avail'
  - alert: InstanceIOWaitCrit
    expr: max by(instance) (irate(node_cpu{mode="iowait"}[5m])) * 100 > 80
    for: 5m
    labels:
      severity: crit
    annotations:
      SUMMARY: '{{$labels.instance}} sustained iowait at {{ printf "%3.2f" $value }}%'
- name: beta_puppet_alerts
  rules:
  - alert: PuppetHugeFail
    expr: (sum(puppet_agent_failed) / count(puppet_agent_failed)) * 100 > 7
    for: 2m
    labels:
      severity: crit
    annotations:
      SUMMARY: 'Puppet widespread failure: {{ printf "%3.2f" $value }}%'
  - alert: meta_PuppetHugeFail
    expr: absent((sum(puppet_agent_failed) / count(puppet_agent_failed)) * 100)
    for: 10m
    labels:
      severity: crit
    annotations:
      SUMMARY: Data not found for PuppetHugeFail
  - alert: PuppetFail
    expr: puppet_agent_failed == 1
    for: 2m
    labels:
      severity: warn
    annotations:
      LOGS: https://logstash-beta.wmflabs.org/app/kibana#/dashboard/66ed4030-782f-11e7-b59f-bdb74a2a8a82?_g=(time:(from:now-1h,mode:quick,to:now))&_a=(filters:!((query:(match:(host:(query:{{
        reReplaceAll ":\\d+" "" $labels.instance }},type:phrase))),meta:(alias:!n,disabled:!f,index:'logstash-*',key:host,negate:!f,value:{{
        reReplaceAll ":\\d+" "" $labels.instance }})),(meta:(alias:!n,disabled:!f,index:'logstash-*',key:program,negate:!f,value:puppet-agent),query:(match:(program:(query:puppet-agent,type:phrase)))),(meta:(alias:!n,disabled:!f,index:'logstash-*',key:level,negate:!f,value:ERROR),query:(match:(level:(query:ERROR,type:phrase))))))
      OPEN_TASK: https://phabricator.wikimedia.org/maniphest/task/create/?title=Puppet
        failure on {{$labels.instance}}&projects=Beta-Cluster-Infrastructure&description=Puppet
        has failed on {{$labels.instance}}
      SUMMARY: Puppet failed on {{$labels.instance}}
  - alert: PuppetStale
    expr: time() - puppet_agent_last_run > (60 * 35)
    for: 5m
    labels:
      severity: warn
    annotations:
      LOGS: https://logstash-beta.wmflabs.org/app/kibana#/dashboard/puppet
      SUMMARY: Puppet stale on {{$labels.instance}} for {{$value | humanizeDuration}}
