- labels:
    shard: multi
    role: slave
  targets:
  - labsdb1009:9104
  - labsdb1010:9104
  - labsdb1011:9104
  - labsdb1012:9104
- labels:
    shard: s1
    role: slave
  targets:
  - db1124:13311
- labels:
    shard: s2
    role: slave
  targets:
  - db1125:13312
- labels:
    shard: s3
    role: slave
  targets:
  - db1124:13313
- labels:
    shard: s4
    role: slave
  targets:
  - db1125:13314
- labels:
    shard: s5
    role: slave
  targets:
  - db1124:13315
- labels:
    shard: s6
    role: slave
  targets:
  - db1125:13316
- labels:
    shard: s7
    role: slave
  targets:
  - db1125:13317
- labels:
    shard: s8
    role: slave
  targets:
  - db1124:13318
