- labels:
    shard: m1
    role: master
  targets:
  - db1063:9104

- labels:
    shard: m1
    role: slave
  targets:
  - db1065:9104

- labels:
    shard: m2
    role: master
  targets:
  - db1051:9104

- labels:
    shard: m3
    role: master
  targets:
  - db1059:9104

- labels:
    shard: m3
    role: slave
  targets:
  - db1053:9104

- labels:
    shard: m4
    role: master
  targets:
  - db1107:9104

- labels:
    shard: m4
    role: slave
  targets:
  - db1108:9104

- labels:
    shard: m5
    role: master
  targets:
  - db1073:9104

- labels:
    shard: tendril
    role: standalone
  targets:
  - db1115:9104

