- labels:
    shard: s1
    role: slave
  targets:
  - db2094:13311
- labels:
    shard: s2
    role: slave
  targets:
  - db2095:13312
- labels:
    shard: s3
    role: slave
  targets:
  - db2094:13313
- labels:
    shard: s4
    role: slave
  targets:
  - db2095:13314
- labels:
    shard: s5
    role: slave
  targets:
  - db2094:13315
- labels:
    shard: s6
    role: slave
  targets:
  - db2095:13316
- labels:
    shard: s7
    role: slave
  targets:
  - db2095:13317
- labels:
    shard: s8
    role: slave
  targets:
  - db2094:13318
