- labels:
    shard: s1
    role: slave
  targets:
  - dbstore2001:13311
  - dbstore2002:13311

- labels:
    shard: s2
    role: slave
  targets:
  - dbstore2001:13312
  - dbstore2002:13312

- labels:
    shard: s3
    role: slave
  targets:
  - dbstore2001:13313
  - dbstore2002:13313

- labels:
    shard: s4
    role: slave
  targets:
  - dbstore2001:13314
  - dbstore2002:13314

- labels:
    shard: x1
    role: slave
  targets:
  - dbstore2001:13320
  - dbstore2002:13320

