- labels:
    shard: s1
    role: slave
  targets:
  - db1080:9104
  - db1083:9104
  - db1089:9104
  - db1099:13311
  - db1105:13311
  - db1106:9104
  - db1118:9104
  - db1119:9104
  - db1134:9104
- labels:
    shard: s1
    role: master
  targets:
  - db1067:9104

- labels:
    shard: s2
    role: slave
  targets:
  - db1074:9104
  - db1076:9104
  - db1090:13312
  - db1103:13312
  - db1105:13312
  - db1122:9104
  - db1129:9104
- labels:
    shard: s2
    role: master
  targets:
  - db1066:9104

- labels:
    shard: s3
    role: slave
  targets:
  - db1078:9104
  - db1112:9104
  - db1123:9104
- labels:
    shard: s3
    role: master
  targets:
  - db1075:9104

- labels:
    shard: s4
    role: slave
  targets:
  - db1084:9104
  - db1091:9104
  - db1097:13314
  - db1103:13314
  - db1121:9104
  - db1138:9104
- labels:
    shard: s4
    role: master
  targets:
  - db1081:9104

- labels:
    shard: s5
    role: slave
  targets:
  - db1082:9104
  - db1096:13315
  - db1097:13315
  - db1100:9104
  - db1110:9104
  - db1113:13315
  - db1130:9104
- labels:
    shard: s5
    role: master
  targets:
  - db1070:9104

- labels:
    shard: s6
    role: slave
  targets:
  - db1085:9104
  - db1088:9104
  - db1093:9104
  - db1096:13316
  - db1098:13316
  - db1113:13316
  - db1131:9104
- labels:
    shard: s6
    role: master
  targets:
  - db1061:9104

- labels:
    shard: s7
    role: slave
  targets:
  - db1079:9104
  - db1086:9104
  - db1090:13317
  - db1094:9104
  - db1098:13317
  - db1101:13317
  - db1136:9104
- labels:
    shard: s7
    role: master
  targets:
  - db1062:9104

- labels:
    shard: s8
    role: slave
  targets:
  - db1087:9104
  - db1092:9104
  - db1099:13318
  - db1101:13318
  - db1104:9104
  - db1109:9104
  - db1126:9104
- labels:
    shard: s8
    role: master
  targets:
  - db1071:9104

- labels:
    shard: x1
    role: slave
  targets:
  - db1069:9104
  - db1127:9104
  - db1137:9104
- labels:
    shard: x1
    role: master
  targets:
  - db1120:9104

- labels:
    shard: es1
    role: standalone
  targets:
  - es1012:9104
  - es1016:9104
  - es1018:9104

- labels:
    shard: es2
    role: slave
  targets:
  - es1011:9104
  - es1013:9104
- labels:
    shard: es2
    role: master
  targets:
  - es1015:9104

- labels:
    shard: es3
    role: slave
  targets:
  - es1014:9104
  - es1019:9104
- labels:
    shard: es3
    role: master
  targets:
  - es1017:9104
- labels:
    shard: test-s4
    role: slave
  targets:
  - db1077:9104
- labels:
    shard: test-s4
    role: master
  targets:
  - db1111:9104
- labels:
    shard: test-s1
    role: slave
  targets:
  - db1114:9104

