- labels:
    shard: s1
    role: slave
  targets:
  - db2055:9104
  - db2062:9104
  - db2070:9104
  - db2071:9104
  - db2072:9104
  - db2088:13311
  - db2085:13311
  - db2092:9104
  - db2103:9104
  - db2112:9104
  - db2116:9104
- labels:
    shard: s1
    role: master
  targets:
  - db2048:9104

- labels:
    shard: s2
    role: slave
  targets:
  - db2041:9104
  - db2049:9104
  - db2056:9104
  - db2063:9104
  - db2088:13312
  - db2091:13312
- labels:
    shard: s2
    role: master
  targets:
  - db2035:9104

- labels:
    shard: s3
    role: slave
  targets:
  - db2036:9104
  - db2050:9104
  - db2057:9104
  - db2074:9104
- labels:
    shard: s3
    role: master
  targets:
  - db2043:9104

- labels:
    shard: s4
    role: slave
  targets:
  - db2058:9104
  - db2065:9104
  - db2073:9104
  - db2084:13314
  - db2091:13314
- labels:
    shard: s4
    role: master
  targets:
  - db2051:9104

- labels:
    shard: s5
    role: slave
  targets:
  - db2038:9104
  - db2059:9104
  - db2066:9104
  - db2075:9104
  - db2084:13315
  - db2089:13315
- labels:
    shard: s5
    role: master
  targets:
  - db2052:9104

- labels:
    shard: s6
    role: slave
  targets:
  - db2046:9104
  - db2053:9104
  - db2060:9104
  - db2067:9104
  - db2076:9104
  - db2087:13316
  - db2089:13316
  - db2117:9104
- labels:
    shard: s6
    role: master
  targets:
  - db2039:9104

- labels:
    shard: s7
    role: slave
  targets:
  - db2040:9104
  - db2054:9104
  - db2061:9104
  - db2068:9104
  - db2077:9104
  - db2086:13317
  - db2087:13317
- labels:
    shard: s7
    role: master
  targets:
  - db2047:9104

- labels:
    shard: s8
    role: slave
  targets:
  - db2080:9104
  - db2081:9104
  - db2082:9104
  - db2083:9104
  - db2085:13318
  - db2086:13318
- labels:
    shard: s8
    role: master
  targets:
  - db2079:9104

- labels:
    shard: es1
    role: standalone
  targets:
  - es2011:9104
  - es2012:9104
  - es2013:9104

- labels:
    shard: es2
    role: slave
  targets:
  - es2014:9104
  - es2016:9104
- labels:
    shard: es2
    role: master
  targets:
  - es2015:9104

- labels:
    shard: es3
    role: slave
  targets:
  - es2017:9104
  - es2019:9104
- labels:
    shard: es3
    role: master
  targets:
  - es2018:9104

- labels:
    shard: x1
    role: slave
  targets:
  - db2034:9104
  - db2069:9104
  - db2096:9104
  - db2115:9104

- labels:
    shard: x1
    role: master
  targets:
  - db2045:9104

- labels:
    shard: test-s1
    role: slave
  targets:
  - db2102:9104
