- labels:
    shard: pc1
    role: slave
  targets:
  - pc1010:9104
- labels:
    shard: pc1
    role: master
  targets:
  - pc1007:9104

- labels:
    shard: pc2
    role: master
  targets:
  - pc1008:9104

- labels:
    shard: pc3
    role: master
  targets:
  - pc1009:9104

