# SPDX-License-Identifier: Apache-2.0
Status: resolved
Receiver: example_receiver
GroupLabels:
  alertname: airDown
  service: prometheus
CommonLabels:
  alertname: airDown
  job: air
  service: prometheus
  severity: ticket
  zone: global
CommonAnnotations:
  runbook: https://runbook.com
  dashboard: https://dashboard.com
  zone: global
ExternalURL: https://prometheus.example.com/alertmanager
Alerts:
  - Annotations:
      summary: service /prometheus air down on instance1
      description: service /prometheus has irc gateway down on instance1
    endsAt: '2017-05-15T13:50:37.835Z'
    generatorURL: https://prometheus.example.com/prometheus/...
    fingerprint: 66214a361160fb6f
    labels:
      alertname: airDown
      instance: instance1:3456
      job: air
      service: prometheus
      severity: ticket
      zone: global
    startsAt: '2017-05-15T13:49:37.834Z'
    status: resolved
  - Annotations:
      summary: service /prometheus air down on instance2
      description: service /prometheus has irc gateway down on instance2
    endsAt: '2017-05-15T11:48:37.834Z'
    generatorURL: https://prometheus.example.com/prometheus/...
    fingerprint: 25a874c99325d1ce
    labels:
      alertname: airDown
      instance: instance2:7890
      job: air
      service: prometheus
      severity: ticket
      zone: global
    startsAt: '2017-05-15T11:47:37.834Z'
    status: resolved
