# Main microservices
parsoid: [eqiad, codfw]
restbase: [eqiad, codfw]
restbase-async: [eqiad, codfw]
search: [eqiad, codfw]
# All the rest
apertium: [eqiad, codfw]
aqs: [eqiad]
citoid: [eqiad, codfw]
cxserver: [eqiad, codfw]
eventbus: [eqiad, codfw]
eventstreams: [eqiad, codfw]
graphoid: [eqiad, codfw]
kartotherian: [eqiad, codfw]
logstash: [eqiad]
mathoid: [eqiad, codfw]
mobileapps: [eqiad, codfw]
ores: [eqiad, codfw]
pdfrender: [eqiad, codfw]
"recommendation-api": [eqiad, codfw]
wdqs: [eqiad, codfw]
wdqs-internal: [eqiad, codfw]
zotero: [eqiad, codfw]
druid-public-broker: [eqiad]
proton: [eqiad, codfw]
blubberoid: [eqiad, codfw]
eventgate-analytics: [eqiad, codfw]
eventgate-main: [eqiad, codfw]
docker-registry: [eqiad, codfw]
sessionstore: [eqiad, codfw]
