# Main microservices
restbase-async: [eqiad, codfw]
restbase-backend: [eqiad, codfw]
restbase: [eqiad, codfw]
search: [eqiad, codfw]
# All the rest
apertium: [eqiad, codfw]
api-gateway: [eqiad, codfw]
apt: [eqiad, codfw]
apus: [eqiad, codfw]
k8s-ingress-aux: [eqiad]
citoid: [eqiad, codfw]
config-master: [eqiad, codfw]
cxserver: [eqiad, codfw]
datahubsearch: [eqiad]
device-analytics: [eqiad, codfw]
docker-registry: [eqiad, codfw]
druid-public-broker: [eqiad]
echostore: [eqiad, codfw]
eventgate-analytics-external: [eqiad, codfw]
eventgate-analytics: [eqiad, codfw]
eventgate-logging-external: [eqiad, codfw]
eventgate-main: [eqiad, codfw]
eventstreams-internal: [eqiad, codfw]
eventstreams: [eqiad, codfw]
helm-charts: [eqiad, codfw]
inference-staging: [codfw]
inference: [eqiad, codfw]
k8s-ingress-staging: [eqiad, codfw]
k8s-ingress-ml-staging: [codfw]
k8s-ingress-ml-serve: [eqiad, codfw]
k8s-ingress-wikikube-ro: [eqiad, codfw]
k8s-ingress-wikikube-rw: [eqiad, codfw]
k8s-ingress-dse: [eqiad]
kartotherian: [eqiad, codfw]
linkrecommendation: [eqiad, codfw]
logstash: [eqiad, codfw]
mathoid: [eqiad, codfw]
mobileapps: [eqiad, codfw]
mwdebug: [eqiad, codfw]
mw-web: [eqiad, codfw]
mw-web-ro: [eqiad, codfw]
mw-api-ext: [eqiad, codfw]
mw-api-ext-ro: [eqiad, codfw]
mw-api-int: [eqiad, codfw]
mw-api-int-ro: [eqiad, codfw]
mw-jobrunner: [eqiad, codfw]
mw-parsoid: [eqiad, codfw]
mw-wikifunctions: [eqiad, codfw]
mw-wikifunctions-ro: [eqiad, codfw]
netbox: [eqiad, codfw]
proton: [eqiad, codfw]
puppetboard: [eqiad, codfw]
puppetdb-api: [eqiad, codfw]
pki: [eqiad, codfw]
push-notifications: [eqiad, codfw]
recommendation-api: [eqiad, codfw]
releases: [eqiad, codfw]
rest-gateway: [eqiad, codfw]
schema: [eqiad, codfw]
sessionstore: [eqiad, codfw]
shellbox-constraints: [eqiad, codfw]
shellbox-media: [eqiad, codfw]
shellbox-syntaxhighlight: [eqiad, codfw]
shellbox-timeline: [eqiad, codfw]
shellbox-video: [eqiad, codfw]
shellbox: [eqiad, codfw]
tegola-vector-tiles: [eqiad, codfw]
termbox: [eqiad, codfw]
thanos-query: [eqiad, codfw]
thanos-swift: [eqiad, codfw]
thanos-web: [eqiad, codfw]
toolhub: [eqiad, codfw]
wcqs: [eqiad, codfw]
wdqs: [eqiad, codfw]
wdqs-internal: [eqiad, codfw]
wdqs-main: [eqiad, codfw]
wdqs-scholarly: [eqiad, codfw]
wikifeeds: [eqiad, codfw]
zotero: [eqiad, codfw]
