# Main microservices
restbase-async: [eqiad, codfw]
restbase-backend: [eqiad, codfw]
restbase: [eqiad, codfw]
search: [eqiad, codfw]
# All the rest
apertium: [eqiad, codfw]
api-gateway: [eqiad, codfw]
apple-search: [eqiad, codfw]
apt: [eqiad, codfw]
aqs: [eqiad, codfw]
blubberoid: [eqiad, codfw]
citoid: [eqiad, codfw]
cxserver: [eqiad, codfw]
datahubsearch: [eqiad]
docker-registry: [eqiad, codfw]
druid-public-broker: [eqiad]
echostore: [eqiad, codfw]
eventgate-analytics: [eqiad, codfw]
eventgate-analytics-external: [eqiad, codfw]
eventgate-logging-external: [eqiad, codfw]
eventgate-main: [eqiad, codfw]
eventstreams: [eqiad, codfw]
eventstreams-internal: [eqiad, codfw]
helm-charts: [eqiad, codfw]
k8s-ingress-staging: [eqiad, codfw]
k8s-ingress-wikikube-ro: [eqiad, codfw]
k8s-ingress-wikikube-rw: [eqiad, codfw]
kartotherian: [eqiad, codfw]
linkrecommendation: [eqiad, codfw]
mathoid: [eqiad, codfw]
mobileapps: [eqiad, codfw]
mwdebug: [eqiad, codfw]
netbox: [eqiad, codfw]
ores: [eqiad, codfw]
proton: [eqiad, codfw]
push-notifications: [eqiad, codfw]
recommendation-api: [eqiad, codfw]
releases: [eqiad, codfw]
schema: [eqiad, codfw]
sessionstore: [eqiad, codfw]
shellbox: [eqiad, codfw]
shellbox-constraints: [eqiad, codfw]
shellbox-media: [eqiad, codfw]
shellbox-syntaxhighlight: [eqiad, codfw]
shellbox-timeline: [eqiad, codfw]
similar-users: [eqiad, codfw]
tegola-vector-tiles: [eqiad, codfw]
termbox: [eqiad, codfw]
thanos-query: [eqiad, codfw]
thanos-swift: [eqiad, codfw]
toolhub: [eqiad, codfw]
wcqs: [eqiad, codfw]
wdqs: [eqiad, codfw]
wdqs-internal: [eqiad, codfw]
wikifeeds: [eqiad, codfw]
zotero: [eqiad, codfw]
puppetdb-api: [eqiad, codfw]
inference: [eqiad, codfw]
puppetboard: [eqiad, codfw]
