---
mount_nfs: false
mediawiki::hhvm::extra_cli":
    hhvm:
        server:
            light_process_count: 0
profile::kubernetes::deployment_server::git_owner: trebuchet
profile::kubernetes::deployment_server::git_group: wikidev
