base::remote_syslog::enable: false

# ES-specific
elasticsearch::auto_create_index: true
elasticsearch::cluster_name: labs-logstash-eqiad
elasticsearch::expected_nodes: 1
elasticsearch::heap_memory: '5G'
elasticsearch::minimum_master_nodes: 1
elasticsearch::multicast_group: 224.2.2.6
elasticsearch::recover_after_nodes: 1
elasticsearch::recover_after_time: '1m'
# Needed to keep from trying to join cirrussearch cluster
elasticsearch::unicast_hosts:
  - deployment-logstash2.deployment-prep.eqiad.wmflabs
elasticsearch::auto_create_index: '+logstash-*,-*'

# Logstash specific
logstash::filter_workers: 1
logstash::heap_memory_mb: 128

logstash::cluster_hosts:
  - deployment-logstash2.deployment-prep.eqiad.wmflabs

# Kibana
role::kibana::vhost: logstash-beta.wmflabs.org
role::kibana::serveradmin: root@deployment-logstash2.deployment-prep.eqiad.wmflabs
role::kibana::auth_type: none
