profile::base::remote_syslog: []

profile::elasticsearch::instances: {}

# ES-specific
# Override common_settings using hiera and not use elastic module
# merge strategy default_instance_params as it will understand
# that we have 2 clusters (beta-search and labs-logstash-eqiad)
# TODO: refactor with role separation
profile::elasticsearch::common_settings:
    cluster_name: labs-logstash-eqiad
    expected_nodes: 1
    heap_memory: '5G'
    minimum_master_nodes: 1
    recover_after_nodes: 1
    recover_after_time: '1m'
    # Needed to keep from trying to join cirrussearch cluster
    unicast_hosts:
      - deployment-logstash2.deployment-prep.eqiad.wmflabs
    auto_create_index: '+logstash-*,-*'
    cluster_hosts:
      - deployment-logstash2.deployment-prep.eqiad.wmflabs
profile::elasticsearch::version: '5.6'
profile::elasticsearch::config_version: '5'
# Kibana
role::kibana::vhost: logstash-beta.wmflabs.org
role::kibana::serveradmin: root@deployment-logstash2.deployment-prep.eqiad.wmflabs
role::kibana::auth_type: local
role::kibana::auth_realm: "Logstash (ssh deployment-deploy01.deployment-prep.eqiad.wmflabs sudo cat /root/secrets.txt)"
role::kibana::auth_file: /etc/logstash/htpasswd
