swift:
  swift-fe:
    port: 80
    default_values:
      pooled: 'no'
      weight: 10
    datacenters:
    - eqiad
    - codfw
parsoid:
  parsoid:
    port: 8000
    default_values:
      pooled: 'no'
      weight: 10
    datacenters:
    - eqiad
    - codfw
elasticsearch:
  elasticsearch:
    port: 9200
    default_values:
      pooled: 'no'
      weight: 10
    datacenters:
    - eqiad
    - codfw
  elasticsearch-ssl:
    port: 9243
    default_values:
      pooled: 'no'
      weight: 10
    datacenters:
    - eqiad
    - codfw
rcstream:
  nginx:
    port: 80
    default_values:
      pooled: 'no'
      weight: 10
    datacenters:
    - eqiad
  nginx_ssl:
    port: 443
    default_values:
      pooled: 'no'
      weight: 10
    datacenters:
    - eqiad
pdf:
  ocg:
    port: 8000
    default_values:
      pooled: 'no'
      weight: 10
    datacenters:
    - eqiad
sca:
  zotero:
    port: 1969
    default_values:
      pooled: 'no'
      weight: 10
    datacenters:
    - eqiad
    - codfw
  apertium:
    port: 2737
    default_values:
      pooled: 'no'
      weight: 10
    datacenters:
    - eqiad
    - codfw
scb:
  mobileapps:
    port: 8888
    default_values:
      pooled: 'yes'
      weight: 10
    datacenters:
    - eqiad
    - codfw
  mathoid:
    port: 10042
    default_values:
      pooled: 'no'
      weight: 10
    datacenters:
    - eqiad
    - codfw
  graphoid:
    port: 19000
    default_values:
      pooled: 'no'
      weight: 10
    datacenters:
    - eqiad
    - codfw
  citoid:
    port: 1970
    default_values:
      pooled: 'no'
      weight: 10
    datacenters:
    - eqiad
    - codfw
  cxserver:
    port: 8080
    default_values:
      pooled: 'no'
      weight: 10
    datacenters:
    - eqiad
    - codfw
  ores:
    port: 8081
    default_values:
      pooled: 'no'
      weight: 10
    datacenters:
    - eqiad
    - codfw
restbase:
  restbase:
    port: 7231
    default_values:
      pooled: 'no'
      weight: 10
    datacenters:
    - eqiad
    - codfw
maps:
  kartotherian:
    port: 6533
    default_values:
      pooled: 'no'
      weight: 10
    datacenters:
    - codfw
aqs:
  aqs:
    port: 7232
    default_values:
      pooled: 'no'
      weight: 10
    datacenters:
    - eqiad
eventbus:
  eventbus:
    port: 8085
    datacenters:
    - eqiad
    - codfw
    default_values:
      pooled: 'yes'
      weight: 10
