# SPDX-License-Identifier: Apache-2.0
groups:
- name: traffic
  rules:
  # **DO NOT** simply take a sum(site_job:varnish_requests:availXm) or a sum(site_cluster:nginx_requests:availXm)
  # expecting those aggregate values to be meaningful!
  # By doing so, you are taking a sum of ratios that have wildly different denominators.
  # Use the 'job:foo_requests:availXm' aggregates instead of 'site_job:'.
  - record: site_job:varnish_requests:avail5m
    expr: sum by(site, job) (job_method_status:varnish_requests:rate5m{status=~"5.."})
      / sum by(site, job) (job_method_status:varnish_requests:rate5m{status=~"[12345].."})
  - record: global_job:varnish_requests:avail5m
    expr: sum by(job) (job_method_status:varnish_requests:rate5m{status=~"5.."})
      / sum by(job) (job_method_status:varnish_requests:rate5m{status=~"[12345].."})
  - record: site_cluster:nginx_requests:avail5m
    expr: sum by(site, cluster) (cluster_status:nginx_http_requests_total:rate5m{status=~"5.."})
      / sum by(site, cluster) (cluster_status:nginx_http_requests_total:rate5m{status=~"[12345].."})
  - record: global_job:nginx_requests:avail5m
    expr: sum by(cluster) (cluster_status:nginx_http_requests_total:rate5m{status=~"5.."})
      / sum by(cluster) (cluster_status:nginx_http_requests_total:rate5m{status=~"[12345].."})
  - record: site_job_backend:varnish_backend_requests:avail5m
    expr: sum by(backend, site, job) (job_method_status_backend:varnish_backend_requests_seconds_count:rate5m{status=~"5.."})
      / sum by(backend, site, job) (job_method_status_backend:varnish_backend_requests_seconds_count:rate5m{status=~"[12345].."})
  - record: site_job_backend:trafficserver_backend_requests:avail5m
    expr: sum by(backend, site, job) (job_method_status_backend_layer:trafficserver_backend_requests_seconds_count:rate5m{status=~"5.."})
      / sum by(backend, site, job) (job_method_status_backend_layer:trafficserver_backend_requests_seconds_count:rate5m{status=~"[12345].."})
  - record: site_job:varnish_requests:avg1d
    expr: sum by(site, job) (avg_over_time(job_method_status:varnish_requests:rate5m[1d]))
  - record: site_job:varnish_requests:avg7d
    expr: sum by(site, job) (avg_over_time(job_method_status:varnish_requests:rate5m[1w]))
  - record: site_job:varnish_requests:avail2m
    expr: sum by(site, job) (job_method_status:varnish_requests:rate2m{status=~"5.."})
      / sum by(site, job) (job_method_status:varnish_requests:rate2m{status=~"[12345].."})
  - record: global_job:varnish_requests:avail2m
    expr: sum by(job) (job_method_status:varnish_requests:rate2m{status=~"5.."})
      / sum by(job) (job_method_status:varnish_requests:rate2m{status=~"[12345].."})
  - record: site_cluster:nginx_requests:avail2m
    expr: sum by(site, cluster) (cluster_status:nginx_http_requests_total:rate2m{status=~"5.."})
      / sum by(site, cluster) (cluster_status:nginx_http_requests_total:rate2m{status=~"[12345].."})
  - record: global_job:nginx_requests:avail2m
    expr: sum by(cluster) (cluster_status:nginx_http_requests_total:rate2m{status=~"5.."})
      / sum by(cluster) (cluster_status:nginx_http_requests_total:rate2m{status=~"[12345].."})
  - record: site_cluster_layer:trafficserver_requests:avail5m
    expr: sum by(site, cluster, layer) (cluster_layer_code:trafficserver_responses_total:rate5m{code=~"5.."})
      / sum by(site, cluster, layer) (cluster_layer_code:trafficserver_responses_total:rate5m{code=~"[12345].."})
  - record: global_job:trafficserver_requests:avail5m
    expr: sum by(cluster, layer) (cluster_layer_code:trafficserver_responses_total:rate5m{code=~"5.."})
      / sum by(cluster, layer) (cluster_layer_code:trafficserver_responses_total:rate5m{code=~"[12345].."})
  - record: site_cluster_layer:trafficserver_requests:avail2m
    expr: sum by(site, cluster, layer) (cluster_layer_code:trafficserver_responses_total:rate2m{code=~"5.."})
      / sum by(site, cluster, layer) (cluster_layer_code:trafficserver_responses_total:rate2m{code=~"[12345].."})
  - record: global_job:trafficserver_requests:avail2m
    expr: sum by(cluster, layer) (cluster_layer_code:trafficserver_responses_total:rate2m{code=~"5.."})
      / sum by(cluster, layer) (cluster_layer_code:trafficserver_responses_total:rate2m{code=~"[12345].."})
  - record: site_cluster:haproxy_requests:avail2m
    expr: sum by(site, cluster) (cluster_code:haproxy_frontend_http_responses_total:rate2m{code="5xx"})
      / sum by(site, cluster) (cluster_code:haproxy_frontend_http_responses_total:rate2m{code=~"[12345]xx"})
  - record: global_job:haproxy_requests:avail2m
    expr: sum by(cluster) (cluster_code:haproxy_frontend_http_responses_total:rate2m{code="5xx"})
      / sum by(cluster) (cluster_code:haproxy_frontend_http_responses_total:rate2m{code=~"[12345]xx"})

- name: jobs
  rules:
  - record: site_job:up:avail
    expr: sum by (job, site) (up) / count by (job, site) (up)
