repo_config:
  integration/mediawiki-tools-codesniffer:
    upstream: https://gerrit.wikimedia.org/r/mediawiki/tools/codesniffer
  integration/phpunit:
    upstream: https://gerrit.wikimedia.org/r/integration/phpunit
  integration/phpcs:
    upstream: https://gerrit.wikimedia.org/r/integration/phpcs
  integration/php-coveralls:
    upstream: https://gerrit.wikimedia.org/r/integration/php-coveralls
  integration/slave-scripts:
    upstream: https://gerrit.wikimedia.org/r/integration/jenkins
    checkout_submodules: true
  jobrunner/jobrunner:
    upstream: https://gerrit.wikimedia.org/r/mediawiki/services/jobrunner
    service_name: jobrunner
  parsoid/deploy:
    upstream: https://gerrit.wikimedia.org/r/p/mediawiki/services/parsoid/deploy
    checkout_submodules: true
    service_name: parsoid
  eventlogging/eventlogging:
    upstream: https://gerrit.wikimedia.org/r/eventlogging
    checkout_submodules: true
  # eventlogging/eventbus is the eventlogging codebase, but as a
  # separate deploy target so that eventlogging-service-eventbus
  # deployments can be scheduled separately from other eventlogging
  # codebase deployments.
  eventlogging/eventbus:
    upstream: https://gerrit.wikimedia.org/r/eventlogging
    checkout_submodules: true
  ocg/ocg:
    upstream: https://gerrit.wikimedia.org/r/mediawiki/services/ocg-collection
    service_name: ocg
    checkout_submodules: true
  mathoid/deploy:
    upstream: https://gerrit.wikimedia.org/r/mediawiki/services/mathoid/deploy
    service_name: mathoid
    checkout_submodules: true
  citoid/deploy:
    upstream: https://gerrit.wikimedia.org/r/mediawiki/services/citoid/deploy
    service_name: citoid
    checkout_submodules: true
  zotero/translation-server:
    upstream: https://gerrit.wikimedia.org/r/mediawiki/services/zotero/translation-server
    service_name: zotero
  zotero/translators:
    upstream: https://gerrit.wikimedia.org/r/mediawiki/services/zotero/translators
  rcstream/rcstream:
    upstream: https://gerrit.wikimedia.org/r/mediawiki/services/rcstream
    service_name: rcstream
  restbase/deploy:
    upstream: https://gerrit.wikimedia.org/r/mediawiki/services/restbase/deploy
    service_name: restbase
    checkout_submodules: true
  fluoride/fluoride:
    upstream: https://gerrit.wikimedia.org/r/mediawiki/tools/fluoride
  statsv/statsv:
    upstream: https://gerrit.wikimedia.org/r/analytics/statsv
  test/testrepo:
    service_name: puppet
    checkout_submodules: true
  elasticsearch/plugins:
    gitfat_enabled: true
    upstream: https://gerrit.wikimedia.org/r/operations/software/elasticsearch/plugins
  analytics/refinery:
    gitfat_enabled: true
    upstream: https://gerrit.wikimedia.org/r/analytics/refinery
  scholarships/scholarships:
    upstream: https://gerrit.wikimedia.org/r/wikimedia/wikimania-scholarships
  librenms/librenms:
    upstream: https://gerrit.wikimedia.org/r/operations/software/librenms
  servermon/servermon:
    service_name: gunicorn
  iegreview/iegreview:
    grain: iegreview
    upstream: https://gerrit.wikimedia.org/r/wikimedia/iegreview
  dropwizard/metrics:
    gitfat_enabled: true
    upstream: https://gerrit.wikimedia.org/r/operations/software/dropwizard-metrics
  cassandra/metrics-collector:
    gitfat_enabled: true
    upstream: https://gerrit.wikimedia.org/r/operations/software/cassandra-metrics-collector
  wdqs/wdqs:
    gitfat_enabled: true
    upstream: https://gerrit.wikimedia.org/r/wikidata/query/deploy
    checkout_submodules: true
  sentry/sentry:
    upstream: https://gerrit.wikimedia.org/r/operations/software/sentry
  cassandra/logstash-logback-encoder:
    gitfat_enabled: true
    upstream: https://gerrit.wikimedia.org/r/operations/software/logstash-logback-encoder
  logstash/plugins:
    upstream: https://gerrit.wikimedia.org/r/operations/software/logstash/plugins
  wikimedia/discovery/analytics:
    upstream: https://gerrit.wikimedia.org/r/wikimedia/discovery/analytics
  analytics/aqs/deploy:
    upstream: https://gerrit.wikimedia.org/r/analytics/aqs/deploy
    service_name: aqs
    checkout_submodules: true
  changeprop/deploy:
    upstream: https://gerrit.wikimedia.org/r/mediawiki/services/change-propagation/deploy
    checkout_submodules: true
  dumps/dumps:
    upstream: https://gerrit.wikimedia.org/r/operations/dumps
