profile::calico::kubernetes::etcd_endpoints:
- https://kubetcd2001.codfw.wmnet:2379
- https://kubetcd2002.codfw.wmnet:2379
- https://kubetcd2003.codfw.wmnet:2379
profile::calico::kubernetes::bgp_peers:
- kubernetes2001.codfw.wmnet
- kubernetes2002.codfw.wmnet
- kubernetes2003.codfw.wmnet
- kubernetes2004.codfw.wmnet
- kubernetes2005.codfw.wmnet
- kubernetes2006.codfw.wmnet
- cr1-codfw.wikimedia.org
- cr2-codfw.wikimedia.org
# enable this when coredns has been deployed not before.
# profile::kubernetes::node::kubelet_cluster_dns: "10.192.72.3"
profile::kubernetes::node::kubelet_cluster_domain: 'cluster.local'
