profile::calico::kubernetes::bgp_peers:
- kubernetes2001.codfw.wmnet
- kubernetes2002.codfw.wmnet
- kubernetes2003.codfw.wmnet
- kubernetes2004.codfw.wmnet
- kubernetes2005.codfw.wmnet
- kubernetes2006.codfw.wmnet
- kubernetes2007.codfw.wmnet
- kubernetes2008.codfw.wmnet
- kubernetes2009.codfw.wmnet
- kubernetes2010.codfw.wmnet
- kubernetes2011.codfw.wmnet
- kubernetes2012.codfw.wmnet
- kubernetes2013.codfw.wmnet
- kubernetes2014.codfw.wmnet
- kubernetes2015.codfw.wmnet
- kubernetes2016.codfw.wmnet
- kubernetes2017.codfw.wmnet
- cr1-codfw.wikimedia.org
- cr2-codfw.wikimedia.org
profile::kubernetes::node::kubelet_cluster_dns: "10.192.72.3"
profile::kubernetes::node::kubelet_cluster_domain: 'cluster.local'
profile::rsyslog::kubernetes::kubernetes_url: https://kubemaster.svc.codfw.wmnet:6443
# Define in the private repo
# profile::rsyslog::kubernetes::token
