prometheus::server::memory_chunks: 3145728
prometheus::server::max_chunks_to_persist: 1048576
lvs::realserver::realserver_ips:
 - 10.2.2.25
# A hash containing configuration for kubernetes clusters.
profile::prometheus::kubernetes::clusters:
  k8s:
    enabled: true
    master_host: 'kubemaster.svc.eqiad.wmnet'
    port: 9906
    class_name: role::kubernetes::worker
  k8s-staging:
    enabled: true
    master_host: 'kubestagemaster.svc.eqiad.wmnet'
    port: 9907
    class_name: role::kubernetes::staging::worker
  k8s-mlserve:
    enabled: true
    master_host: 'ml-ctrl.svc.eqiad.wmnet'
    port: 9909
    class_name: role::ml_k8s::worker
    controller_class_name: role::ml_k8s::master
# In the private repo a stanza like the following is required
# profile::prometheus::kubernetes::cluster_tokens:
# k8s:
#   client_token: eqiaddummy
# k8s-staging:
#   client_token: eqiaddummystaging

profile::prometheus::ganeti::clusters:
  - ganeti01.svc.eqiad.wmnet
