profile::calico::kubernetes::etcd_endpoints:
- https://etcd1001.eqiad.wmnet:2379
- https://etcd1002.eqiad.wmnet:2379
- https://etcd1003.eqiad.wmnet:2379
profile::calico::kubernetes::bgp_peers:
- kubernetes1001.eqiad.wmnet
- kubernetes1002.eqiad.wmnet
- kubernetes1003.eqiad.wmnet
- kubernetes1004.eqiad.wmnet
- kubernetes1005.eqiad.wmnet
- kubernetes1006.eqiad.wmnet
- cr1-eqiad.wikimedia.org
- cr2-eqiad.wikimedia.org
# enable this when coredns is deployed not before
# profile::kubernetes::node::kubelet_cluster_dns: "10.64.72.3"
profile::kubernetes::node::kubelet_cluster_domain: 'cluster.local'
